[build]
  # Directory to change to before starting a build
  base = "client/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "dist/"
  
  # Build command
  command = "npm run build"

# Baidu verification - serve directly without redirects
[[redirects]]
  from = "/baidu_verify_codeva-jt9W1siUJ0.html"
  to = "/baidu_verify_codeva-jt9W1siUJ0.html"
  status = 200
  force = true

[[redirects]]
  from = "/baidu_verify_codeva-uaF9Sbrzcu.html"
  to = "/baidu_verify_codeva-uaF9Sbrzcu.html"
  status = 200
  force = true

# Serve assets normally (must come before language redirects)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Serve static files normally
[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

# Language-specific redirects (must come before catch-all)
[[redirects]]
  from = "/zh"
  to = "/index-zh.html"
  status = 200

# Don't redirect assets when accessed from /zh path
[[redirects]]
  from = "/zh/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/index-zh.html"
  status = 200

# Default English version
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Catch-all redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"