[build]
  # Directory to change to before starting a build
  base = "client/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "dist/"
  
  # Build command
  command = "npm run build"

# Language-specific redirects (must come before catch-all)
[[redirects]]
  from = "/zh"
  to = "/index-zh.html"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/index-zh.html"
  status = 200

# Default English version
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Catch-all redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"